# Generated by Django 5.0.8 on 2024-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20240807_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sales',
            field=models.BigIntegerField(),
        ),
    ]
